# Generated by Django 2.2.6 on 2019-11-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191114_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_num', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=30)),
                ('xposition', models.CharField(max_length=30)),
                ('yposition', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
