# Generated by Django 2.2.6 on 2019-11-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_mapmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCTV_MANAGEMENT', models.CharField(max_length=30)),
                ('CCTV_ADDRESS_NAME', models.CharField(max_length=30)),
                ('CCTV_LONGITUDE', models.CharField(max_length=20)),
                ('CCTV_LATITUDE', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
